-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1 (lin64) Build 6140274 Wed May 21 22:58:25 MDT 2025
-- Date        : Tue Oct 14 12:16:56 2025
-- Host        : cenglab16 running 64-bit Ubuntu 24.04.3 LTS
-- Command     : write_vhdl -force -mode synth_stub
--               /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_microprocessor_0_0/system_microprocessor_0_0_stub.vhdl
-- Design      : system_microprocessor_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7a100tcsg324-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity system_microprocessor_0_0 is
  Port ( 
    CLK : in STD_LOGIC;
    RESET : in STD_LOGIC;
    I_M_AXI_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    I_M_AXI_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    I_M_AXI_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    I_M_AXI_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    I_M_AXI_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    I_M_AXI_AWLOCK : out STD_LOGIC;
    I_M_AXI_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    I_M_AXI_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    I_M_AXI_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    I_M_AXI_AWUSER : out STD_LOGIC_VECTOR ( 0 to 0 );
    I_M_AXI_AWVALID : out STD_LOGIC;
    I_M_AXI_AWREADY : in STD_LOGIC;
    I_M_AXI_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    I_M_AXI_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    I_M_AXI_WLAST : out STD_LOGIC;
    I_M_AXI_WUSER : out STD_LOGIC_VECTOR ( 0 to 0 );
    I_M_AXI_WVALID : out STD_LOGIC;
    I_M_AXI_WREADY : in STD_LOGIC;
    I_M_AXI_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    I_M_AXI_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    I_M_AXI_BUSER : in STD_LOGIC_VECTOR ( 0 to 0 );
    I_M_AXI_BVALID : in STD_LOGIC;
    I_M_AXI_BREADY : out STD_LOGIC;
    I_M_AXI_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    I_M_AXI_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    I_M_AXI_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    I_M_AXI_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    I_M_AXI_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    I_M_AXI_ARLOCK : out STD_LOGIC;
    I_M_AXI_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    I_M_AXI_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    I_M_AXI_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    I_M_AXI_ARUSER : out STD_LOGIC_VECTOR ( 0 to 0 );
    I_M_AXI_ARVALID : out STD_LOGIC;
    I_M_AXI_ARREADY : in STD_LOGIC;
    I_M_AXI_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    I_M_AXI_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    I_M_AXI_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    I_M_AXI_RLAST : in STD_LOGIC;
    I_M_AXI_RUSER : in STD_LOGIC_VECTOR ( 0 to 0 );
    I_M_AXI_RVALID : in STD_LOGIC;
    I_M_AXI_RREADY : out STD_LOGIC;
    D_M_AXI_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    D_M_AXI_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    D_M_AXI_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    D_M_AXI_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    D_M_AXI_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    D_M_AXI_AWLOCK : out STD_LOGIC;
    D_M_AXI_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    D_M_AXI_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    D_M_AXI_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    D_M_AXI_AWUSER : out STD_LOGIC_VECTOR ( 0 to 0 );
    D_M_AXI_AWVALID : out STD_LOGIC;
    D_M_AXI_AWREADY : in STD_LOGIC;
    D_M_AXI_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    D_M_AXI_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    D_M_AXI_WLAST : out STD_LOGIC;
    D_M_AXI_WUSER : out STD_LOGIC_VECTOR ( 0 to 0 );
    D_M_AXI_WVALID : out STD_LOGIC;
    D_M_AXI_WREADY : in STD_LOGIC;
    D_M_AXI_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    D_M_AXI_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    D_M_AXI_BUSER : in STD_LOGIC_VECTOR ( 0 to 0 );
    D_M_AXI_BVALID : in STD_LOGIC;
    D_M_AXI_BREADY : out STD_LOGIC;
    D_M_AXI_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    D_M_AXI_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    D_M_AXI_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    D_M_AXI_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    D_M_AXI_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    D_M_AXI_ARLOCK : out STD_LOGIC;
    D_M_AXI_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    D_M_AXI_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    D_M_AXI_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    D_M_AXI_ARUSER : out STD_LOGIC_VECTOR ( 0 to 0 );
    D_M_AXI_ARVALID : out STD_LOGIC;
    D_M_AXI_ARREADY : in STD_LOGIC;
    D_M_AXI_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    D_M_AXI_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    D_M_AXI_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    D_M_AXI_RLAST : in STD_LOGIC;
    D_M_AXI_RUSER : in STD_LOGIC_VECTOR ( 0 to 0 );
    D_M_AXI_RVALID : in STD_LOGIC;
    D_M_AXI_RREADY : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of system_microprocessor_0_0 : entity is "system_microprocessor_0_0,microprocessor,{}";
  attribute core_generation_info : string;
  attribute core_generation_info of system_microprocessor_0_0 : entity is "system_microprocessor_0_0,microprocessor,{x_ipProduct=Vivado 2025.1,x_ipVendor=xilinx.com,x_ipLibrary=module_ref,x_ipName=microprocessor,x_ipVersion=1.0,x_ipCoreRevision=1,x_ipLanguage=VHDL,x_ipSimLanguage=MIXED,C_M_TARGET_SLAVE_BASE_ADDR=0x00000000,C_M_AXI_BURST_LEN=1,C_M_AXI_ID_WIDTH=1,C_M_AXI_ADDR_WIDTH=32,C_M_AXI_DATA_WIDTH=32,C_M_AXI_AWUSER_WIDTH=1,C_M_AXI_ARUSER_WIDTH=1,C_M_AXI_WUSER_WIDTH=1,C_M_AXI_RUSER_WIDTH=1,C_M_AXI_BUSER_WIDTH=1}";
  attribute downgradeipidentifiedwarnings : string;
  attribute downgradeipidentifiedwarnings of system_microprocessor_0_0 : entity is "yes";
  attribute ip_definition_source : string;
  attribute ip_definition_source of system_microprocessor_0_0 : entity is "module_ref";
end system_microprocessor_0_0;

architecture stub of system_microprocessor_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "CLK,RESET,I_M_AXI_AWID[0:0],I_M_AXI_AWADDR[31:0],I_M_AXI_AWLEN[7:0],I_M_AXI_AWSIZE[2:0],I_M_AXI_AWBURST[1:0],I_M_AXI_AWLOCK,I_M_AXI_AWCACHE[3:0],I_M_AXI_AWPROT[2:0],I_M_AXI_AWQOS[3:0],I_M_AXI_AWUSER[0:0],I_M_AXI_AWVALID,I_M_AXI_AWREADY,I_M_AXI_WDATA[31:0],I_M_AXI_WSTRB[3:0],I_M_AXI_WLAST,I_M_AXI_WUSER[0:0],I_M_AXI_WVALID,I_M_AXI_WREADY,I_M_AXI_BID[0:0],I_M_AXI_BRESP[1:0],I_M_AXI_BUSER[0:0],I_M_AXI_BVALID,I_M_AXI_BREADY,I_M_AXI_ARID[0:0],I_M_AXI_ARADDR[31:0],I_M_AXI_ARLEN[7:0],I_M_AXI_ARSIZE[2:0],I_M_AXI_ARBURST[1:0],I_M_AXI_ARLOCK,I_M_AXI_ARCACHE[3:0],I_M_AXI_ARPROT[2:0],I_M_AXI_ARQOS[3:0],I_M_AXI_ARUSER[0:0],I_M_AXI_ARVALID,I_M_AXI_ARREADY,I_M_AXI_RID[0:0],I_M_AXI_RDATA[31:0],I_M_AXI_RRESP[1:0],I_M_AXI_RLAST,I_M_AXI_RUSER[0:0],I_M_AXI_RVALID,I_M_AXI_RREADY,D_M_AXI_AWID[0:0],D_M_AXI_AWADDR[31:0],D_M_AXI_AWLEN[7:0],D_M_AXI_AWSIZE[2:0],D_M_AXI_AWBURST[1:0],D_M_AXI_AWLOCK,D_M_AXI_AWCACHE[3:0],D_M_AXI_AWPROT[2:0],D_M_AXI_AWQOS[3:0],D_M_AXI_AWUSER[0:0],D_M_AXI_AWVALID,D_M_AXI_AWREADY,D_M_AXI_WDATA[31:0],D_M_AXI_WSTRB[3:0],D_M_AXI_WLAST,D_M_AXI_WUSER[0:0],D_M_AXI_WVALID,D_M_AXI_WREADY,D_M_AXI_BID[0:0],D_M_AXI_BRESP[1:0],D_M_AXI_BUSER[0:0],D_M_AXI_BVALID,D_M_AXI_BREADY,D_M_AXI_ARID[0:0],D_M_AXI_ARADDR[31:0],D_M_AXI_ARLEN[7:0],D_M_AXI_ARSIZE[2:0],D_M_AXI_ARBURST[1:0],D_M_AXI_ARLOCK,D_M_AXI_ARCACHE[3:0],D_M_AXI_ARPROT[2:0],D_M_AXI_ARQOS[3:0],D_M_AXI_ARUSER[0:0],D_M_AXI_ARVALID,D_M_AXI_ARREADY,D_M_AXI_RID[0:0],D_M_AXI_RDATA[31:0],D_M_AXI_RRESP[1:0],D_M_AXI_RLAST,D_M_AXI_RUSER[0:0],D_M_AXI_RVALID,D_M_AXI_RREADY";
  attribute x_interface_info : string;
  attribute x_interface_info of CLK : signal is "xilinx.com:signal:clock:1.0 CLK CLK";
  attribute x_interface_mode : string;
  attribute x_interface_mode of CLK : signal is "slave CLK";
  attribute x_interface_parameter : string;
  attribute x_interface_parameter of CLK : signal is "XIL_INTERFACENAME CLK, ASSOCIATED_BUSIF D_M_AXI:I_M_AXI, ASSOCIATED_RESET RESET, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN /clk_wiz_clk_out1, INSERT_VIP 0";
  attribute x_interface_info of RESET : signal is "xilinx.com:signal:reset:1.0 RESET RST";
  attribute x_interface_mode of RESET : signal is "slave RESET";
  attribute x_interface_parameter of RESET : signal is "XIL_INTERFACENAME RESET, POLARITY ACTIVE_HIGH, INSERT_VIP 0";
  attribute x_interface_info of I_M_AXI_AWID : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWID";
  attribute x_interface_mode of I_M_AXI_AWID : signal is "master I_M_AXI";
  attribute x_interface_parameter of I_M_AXI_AWID : signal is "XIL_INTERFACENAME I_M_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 1, ADDR_WIDTH 32, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 1, RUSER_WIDTH 1, BUSER_WIDTH 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN /clk_wiz_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute x_interface_info of I_M_AXI_AWADDR : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWADDR";
  attribute x_interface_info of I_M_AXI_AWLEN : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWLEN";
  attribute x_interface_info of I_M_AXI_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWSIZE";
  attribute x_interface_info of I_M_AXI_AWBURST : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWBURST";
  attribute x_interface_info of I_M_AXI_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWLOCK";
  attribute x_interface_info of I_M_AXI_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWCACHE";
  attribute x_interface_info of I_M_AXI_AWPROT : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWPROT";
  attribute x_interface_info of I_M_AXI_AWQOS : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWQOS";
  attribute x_interface_info of I_M_AXI_AWUSER : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWUSER";
  attribute x_interface_info of I_M_AXI_AWVALID : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWVALID";
  attribute x_interface_info of I_M_AXI_AWREADY : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI AWREADY";
  attribute x_interface_info of I_M_AXI_WDATA : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI WDATA";
  attribute x_interface_info of I_M_AXI_WSTRB : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI WSTRB";
  attribute x_interface_info of I_M_AXI_WLAST : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI WLAST";
  attribute x_interface_info of I_M_AXI_WUSER : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI WUSER";
  attribute x_interface_info of I_M_AXI_WVALID : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI WVALID";
  attribute x_interface_info of I_M_AXI_WREADY : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI WREADY";
  attribute x_interface_info of I_M_AXI_BID : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI BID";
  attribute x_interface_info of I_M_AXI_BRESP : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI BRESP";
  attribute x_interface_info of I_M_AXI_BUSER : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI BUSER";
  attribute x_interface_info of I_M_AXI_BVALID : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI BVALID";
  attribute x_interface_info of I_M_AXI_BREADY : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI BREADY";
  attribute x_interface_info of I_M_AXI_ARID : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARID";
  attribute x_interface_info of I_M_AXI_ARADDR : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARADDR";
  attribute x_interface_info of I_M_AXI_ARLEN : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARLEN";
  attribute x_interface_info of I_M_AXI_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARSIZE";
  attribute x_interface_info of I_M_AXI_ARBURST : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARBURST";
  attribute x_interface_info of I_M_AXI_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARLOCK";
  attribute x_interface_info of I_M_AXI_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARCACHE";
  attribute x_interface_info of I_M_AXI_ARPROT : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARPROT";
  attribute x_interface_info of I_M_AXI_ARQOS : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARQOS";
  attribute x_interface_info of I_M_AXI_ARUSER : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARUSER";
  attribute x_interface_info of I_M_AXI_ARVALID : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARVALID";
  attribute x_interface_info of I_M_AXI_ARREADY : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI ARREADY";
  attribute x_interface_info of I_M_AXI_RID : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI RID";
  attribute x_interface_info of I_M_AXI_RDATA : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI RDATA";
  attribute x_interface_info of I_M_AXI_RRESP : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI RRESP";
  attribute x_interface_info of I_M_AXI_RLAST : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI RLAST";
  attribute x_interface_info of I_M_AXI_RUSER : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI RUSER";
  attribute x_interface_info of I_M_AXI_RVALID : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI RVALID";
  attribute x_interface_info of I_M_AXI_RREADY : signal is "xilinx.com:interface:aximm:1.0 I_M_AXI RREADY";
  attribute x_interface_info of D_M_AXI_AWID : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWID";
  attribute x_interface_mode of D_M_AXI_AWID : signal is "master D_M_AXI";
  attribute x_interface_parameter of D_M_AXI_AWID : signal is "XIL_INTERFACENAME D_M_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 1, ADDR_WIDTH 32, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 1, RUSER_WIDTH 1, BUSER_WIDTH 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN /clk_wiz_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute x_interface_info of D_M_AXI_AWADDR : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWADDR";
  attribute x_interface_info of D_M_AXI_AWLEN : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWLEN";
  attribute x_interface_info of D_M_AXI_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWSIZE";
  attribute x_interface_info of D_M_AXI_AWBURST : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWBURST";
  attribute x_interface_info of D_M_AXI_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWLOCK";
  attribute x_interface_info of D_M_AXI_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWCACHE";
  attribute x_interface_info of D_M_AXI_AWPROT : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWPROT";
  attribute x_interface_info of D_M_AXI_AWQOS : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWQOS";
  attribute x_interface_info of D_M_AXI_AWUSER : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWUSER";
  attribute x_interface_info of D_M_AXI_AWVALID : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWVALID";
  attribute x_interface_info of D_M_AXI_AWREADY : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI AWREADY";
  attribute x_interface_info of D_M_AXI_WDATA : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI WDATA";
  attribute x_interface_info of D_M_AXI_WSTRB : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI WSTRB";
  attribute x_interface_info of D_M_AXI_WLAST : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI WLAST";
  attribute x_interface_info of D_M_AXI_WUSER : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI WUSER";
  attribute x_interface_info of D_M_AXI_WVALID : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI WVALID";
  attribute x_interface_info of D_M_AXI_WREADY : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI WREADY";
  attribute x_interface_info of D_M_AXI_BID : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI BID";
  attribute x_interface_info of D_M_AXI_BRESP : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI BRESP";
  attribute x_interface_info of D_M_AXI_BUSER : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI BUSER";
  attribute x_interface_info of D_M_AXI_BVALID : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI BVALID";
  attribute x_interface_info of D_M_AXI_BREADY : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI BREADY";
  attribute x_interface_info of D_M_AXI_ARID : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARID";
  attribute x_interface_info of D_M_AXI_ARADDR : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARADDR";
  attribute x_interface_info of D_M_AXI_ARLEN : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARLEN";
  attribute x_interface_info of D_M_AXI_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARSIZE";
  attribute x_interface_info of D_M_AXI_ARBURST : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARBURST";
  attribute x_interface_info of D_M_AXI_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARLOCK";
  attribute x_interface_info of D_M_AXI_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARCACHE";
  attribute x_interface_info of D_M_AXI_ARPROT : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARPROT";
  attribute x_interface_info of D_M_AXI_ARQOS : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARQOS";
  attribute x_interface_info of D_M_AXI_ARUSER : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARUSER";
  attribute x_interface_info of D_M_AXI_ARVALID : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARVALID";
  attribute x_interface_info of D_M_AXI_ARREADY : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI ARREADY";
  attribute x_interface_info of D_M_AXI_RID : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI RID";
  attribute x_interface_info of D_M_AXI_RDATA : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI RDATA";
  attribute x_interface_info of D_M_AXI_RRESP : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI RRESP";
  attribute x_interface_info of D_M_AXI_RLAST : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI RLAST";
  attribute x_interface_info of D_M_AXI_RUSER : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI RUSER";
  attribute x_interface_info of D_M_AXI_RVALID : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI RVALID";
  attribute x_interface_info of D_M_AXI_RREADY : signal is "xilinx.com:interface:aximm:1.0 D_M_AXI RREADY";
  attribute x_core_info : string;
  attribute x_core_info of stub : architecture is "microprocessor,Vivado 2025.1";
begin
end;
