# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/student/s101153258/riscv_microprocessor/riscv_microprocessor.runs/synth_1/system_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param chipscope.maxJobs 5
set_param general.usePosixSpawnForFork 1
set_param bd.open.in_stealth_mode 2
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-480853-cenglab01/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.cache/wt [current_project]
set_property parent.project_path /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {/home/student/s101153258/.Xilinx/Vivado/2025.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_output_repo /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_0/test_instruction_file.coe
add_files /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_0/op_branch_test.coe
add_files /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_bram_1/microprocessor_test.coe
add_files /opt/packages/op_branch_test.coe
add_files /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_bram_1/load_store_test.coe
add_files /opt/packages/cylon_test.coe
add_files /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/sys_clock/ip/sys_clock_axi_traffic_gen_0_0/data.coe
add_files /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/sys_clock/ip/sys_clock_axi_traffic_gen_0_0/address.coe
add_files /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/sys_clock/ip/sys_clock_axi_traffic_gen_0_0/mask.coe
add_files /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/sys_clock/ip/sys_clock_axi_traffic_gen_0_0/control.coe
read_vhdl -library xil_defaultlib {
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/RISCV_package.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/imports/new/generic_shifter.vhdl
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/alu.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/branch_test_unit.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/imports/new/decoder_pkg.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/imports/new/generic_register.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/register_file.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/program_counter.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/datapath.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/decoder.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/fetch_unit.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/load_store_unit.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/sequencer.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/new/microprocessor.vhd
  /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/hdl/system_wrapper.vhd
}
add_files /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_clk_wiz_0/system_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_clk_wiz_0/system_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_clk_wiz_0/system_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_rst_clk_wiz_100M_0/system_rst_clk_wiz_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_axi_bram_ctrl_0_bram_1/system_axi_bram_ctrl_0_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_1/bd_919a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_2/bd_919a_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_3/bd_919a_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_4/bd_919a_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_5/bd_919a_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_6/bd_919a_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_10/bd_919a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_11/bd_919a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_12/bd_919a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_13/bd_919a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_14/bd_919a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_15/bd_919a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_19/bd_919a_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_20/bd_919a_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_21/bd_919a_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_22/bd_919a_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_23/bd_919a_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_24/bd_919a_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_25/bd_919a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_26/bd_919a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_27/bd_919a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_28/bd_919a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_29/bd_919a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_30/bd_919a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_32/bd_919a_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_33/bd_919a_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_34/bd_919a_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_35/bd_919a_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_36/bd_919a_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_37/bd_919a_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_39/bd_919a_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_40/bd_919a_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_41/bd_919a_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_42/bd_919a_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_43/bd_919a_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_44/bd_919a_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_46/bd_919a_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_47/bd_919a_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_48/bd_919a_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_49/bd_919a_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_50/bd_919a_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_51/bd_919a_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/system_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/utils_1/imports/synth_1/system_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top system_wrapper -part xc7a100tcsg324-1 -directive PerformanceOptimized -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
