# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/system/ip/system_axi_interconnect_0_imp_xbar_0/system_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'system_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_axi_interconnect_0_imp_xbar_0/system_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.srcs/sources_1/bd/system/ip/system_axi_interconnect_0_imp_xbar_0/system_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'system_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student/s101153258/riscv_microprocessor/riscv_microprocessor.gen/sources_1/bd/system/ip/system_axi_interconnect_0_imp_xbar_0/system_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
