#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Oct 07 11:49:26 MDT 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/opt/Xilinx/2025.1/data"

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axi_bram_ctrl_v4_1_13 -L blk_mem_gen_v8_4_11 -L proc_sys_reset_v5_0_17 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot fetch_unit_testbench_behav xil_defaultlib.fetch_unit_testbench xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axi_bram_ctrl_v4_1_13 -L blk_mem_gen_v8_4_11 -L proc_sys_reset_v5_0_17 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot fetch_unit_testbench_behav xil_defaultlib.fetch_unit_testbench xil_defaultlib.glbl -log elaborate.log

