#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 10 14:53:52 MST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/opt/Xilinx/2025.1/data"

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L proc_sys_reset_v5_0_17 -L axi_bram_ctrl_v4_1_13 -L blk_mem_gen_v8_4_11 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_5 -L axi_gpio_v2_0_37 -L generic_baseblocks_v2_1_2 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_35 -L fifo_generator_v13_2_13 -L axi_data_fifo_v2_1_35 -L axi_crossbar_v2_1_37 -L axi_protocol_converter_v2_1_36 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot microprocessor_testbench_behav xil_defaultlib.microprocessor_testbench xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L proc_sys_reset_v5_0_17 -L axi_bram_ctrl_v4_1_13 -L blk_mem_gen_v8_4_11 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_5 -L axi_gpio_v2_0_37 -L generic_baseblocks_v2_1_2 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_35 -L fifo_generator_v13_2_13 -L axi_data_fifo_v2_1_35 -L axi_crossbar_v2_1_37 -L axi_protocol_converter_v2_1_36 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot microprocessor_testbench_behav xil_defaultlib.microprocessor_testbench xil_defaultlib.glbl -log elaborate.log

