#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 17 13:51:20 MST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim microprocessor_testbench_behav -key {Behavioral:sim_1:Functional:microprocessor_testbench} -tclbatch microprocessor_testbench.tcl -protoinst "protoinst_files/system.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view /home/student/s101153258/riscv_microprocessor/testbench/fetch_unit_testbench_behav.wcfg -view /home/student/s101153258/riscv_microprocessor/testbench/microprocessor_testbench_behav.wcfg -log simulate.log"
xsim microprocessor_testbench_behav -key {Behavioral:sim_1:Functional:microprocessor_testbench} -tclbatch microprocessor_testbench.tcl -protoinst "protoinst_files/system.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view /home/student/s101153258/riscv_microprocessor/testbench/fetch_unit_testbench_behav.wcfg -view /home/student/s101153258/riscv_microprocessor/testbench/microprocessor_testbench_behav.wcfg -log simulate.log

