#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Oct 10 13:26:30 MDT 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim RISCV_sequencer_tb_behav -key {Behavioral:sim_1:Functional:RISCV_sequencer_tb} -tclbatch RISCV_sequencer_tb.tcl -view /home/student/s101153258/riscv_microprocessor/testbench/fetch_unit_testbench_behav.wcfg -log simulate.log"
xsim RISCV_sequencer_tb_behav -key {Behavioral:sim_1:Functional:RISCV_sequencer_tb} -tclbatch RISCV_sequencer_tb.tcl -view /home/student/s101153258/riscv_microprocessor/testbench/fetch_unit_testbench_behav.wcfg -log simulate.log

